#### Importing Data

* https://www.kaggle.com/datasets/uciml/iris
* http://archive.ics.uci.edu/ml/datasets/Iris

In [1]:
import pandas as pd

#### CSV File

In [2]:
#Store the dataFrame into a variable
df = pd.read_csv("E:\DATA SETS\Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [3]:
# redefine the index column with Id
df.set_index("Id")

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
#check if are changed if not fix it...
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [5]:
df.set_index("Id", inplace=True)

In [6]:
df.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
# another way when importing data
df = pd.read_csv("E:\DATA SETS\Iris.csv", index_col=0)
df.head()

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
Id
1             5.1           3.5            1.4           0.2  Iris-setosa
2             4.9           3.0            1.4           0.2  Iris-setosa
3             4.7           3.2            1.3           0.2  Iris-setosa
4             4.6           3.1            1.5           0.2  Iris-setosa
5             5.0           3.6            1.4           0.2  Iris-setosa

#### Excel File

In [8]:
!pip install openpyxl

Requirement already satisfied: openpyxl in e:\python bildung\python mini e_degre\masterenv\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in e:\python bildung\python mini e_degre\masterenv\lib\site-packages (from openpyxl) (1.1.0)

In [9]:
import openpyxl

In [10]:
df = pd.read_excel("E:\DATA SETS\Iris.xlsx", index_col=0)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1               51            35             14             2     Iris-setosa
2               49            30             14             2     Iris-setosa
3               47            32             13             2     Iris-setosa
4               46            31             15             2     Iris-setosa
5               50            36             14             2     Iris-setosa
..             ...           ...            ...           ...             ...
146             67            30             52            23  Iris-virginica
147             63            25             50            19  Iris-virginica
148             65            30             52            20  Iris-virginica
149             62            34             54            23  Iris-virginica
150             59            30             51            18  Iris-virginica

[150 rows x 5 columns]

#### file.data

In [11]:
pd.read_table("E:\DATA SETS\iris.data",
              sep=",", 
              header=None,
              names=['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species'] #columns
             )

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
0              5.1           3.5            1.4           0.2     Iris-setosa
1              4.9           3.0            1.4           0.2     Iris-setosa
2              4.7           3.2            1.3           0.2     Iris-setosa
3              4.6           3.1            1.5           0.2     Iris-setosa
4              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
145            6.7           3.0            5.2           2.3  Iris-virginica
146            6.3           2.5            5.0           1.9  Iris-virginica
147            6.5           3.0            5.2           2.0  Iris-virginica
148            6.2           3.4            5.4           2.3  Iris-virginica
149            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [13]:
# The pd.read_clipboard() function is used to read data from the table that has been copied to the clipboard.
pd.read_clipboard()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1             51            35             14             2  Iris-setosa
1   2             49            30             14             2  Iris-setosa
2   3             47            32             13             2  Iris-setosa

#### HTML Pages

In [14]:
!pip install lxml

Requirement already satisfied: lxml in e:\python bildung\python mini e_degre\masterenv\lib\site-packages (4.9.2)

In [15]:
import lxml

In [16]:
!pip show lxml

Name: lxml
Version: 4.9.2
Summary: Powerful and Pythonic XML processing library combining libxml2/libxslt with the ElementTree API.
Home-page: https://lxml.de/
Author: lxml dev team
Author-email: lxml-dev@lxml.de
License: BSD-3-Clause
Location: e:\python bildung\python mini e_degre\masterenv\lib\site-packages
Requires:
Required-by:

In [17]:
pd.read_clipboard()

Empty DataFrame
Columns: [https://en.wikipedia.org/wiki/Timeline_of_programming_languages]
Index: []

In [18]:
dfs = pd.read_html('https://en.wikipedia.org/wiki/Timeline_of_programming_languages')

In [19]:
type(dfs)

list

In [20]:
dfs[5]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1950,Short Code (for UNIVAC I),William F. Schmitt,Short Code
1,1951,Superplan,Heinz Rutishauser,Plankalkül
2,1951,ALGAE,Edward A. Voorhees and Karl Balke,none (unique language)
3,1951,Intermediate Programming Language,Arthur Burks,Short Code
4,1951,Boehm unnamed coding system,Corrado Böhm,CPC Coding scheme
5,1951,Klammerausdrücke,Konrad Zuse,Plankalkül
6,1951,Stanislaus (Notation),Fritz Bauer,none (unique language)
7,1951,Sort Merge Generator,Betty Holberton,none (unique language)
8,1952,Short Code (for UNIVAC II),"Albert B. Tonik,[2] J. R. Logan",Short Code (for UNIVAC I)
9,1952,A-0,Grace Hopper,Short Code
10,1952,Glennie Autocode,Alick Glennie after Alan Turing,CPC Coding scheme
11,1952,Operator programming,Alexey Andreevich Lyapunov with the participat...,MESM
12,1952,Editing Generator,Milly Koss,SORT/MERGE
13,1952,COMPOOL,RAND/SDC,none (unique language)
14,1953,Speedcoding,John W. Backus,none (unique language)
15,1953,READ/PRINT,"Don Harroff, James Fishman, George Ryckman",none (unique language)
16,1954,Laning and Zierler system,"Laning, Zierler, Adams at MIT Project Whirlwind",none (unique language)
17,1954,Mark I Autocode,Tony Brooker,Glennie Autocode
18,1954–55,FORTRAN (concept),Team led by John W. Backus at IBM,Speedcoding
19,1954,ARITH-MATIC,Team led by Grace Hopper at UNIVAC,A-0
20,1954,MATH-MATIC,Team led by Charles Katz,A-0
21,1954,MATRIX MATH,H G Kahrimanian,none (unique language)
22,1954,IPL I (concept),"Allen Newell, Cliff Shaw, Herbert A. Simon",none (unique language)
23,1955,Address programming language (with Pointers),Kateryna Yushchenko,Operator programming - Alexey Andreevich Lyapu...
24,1955,FLOW-MATIC,Team led by Grace Hopper at UNIVAC,A-0
25,1955,BACAIC,M. Grems and R. Porter,NaN
26,1955,PACT I,SHARE,"FORTRAN, A-2"
27,1955,Freiburger Code[3][4],University of Freiburg,—
28,1955–56,Sequentielle Formelübersetzung,Fritz Bauer and Karl Samelson,Boehm
29,1955–56,IT,Team led by Alan Perlis,Laning and Zierler
30,1955,PRINT,IBM,NaN
31,1958,IPL II (implementation),"Allen Newell, Cliff Shaw, Herbert A. Simon",IPL I
32,1956–58,LISP (concept),John McCarthy,IPL
33,1957,COMTRAN,Bob Bemer,FLOW-MATIC
34,1957,GEORGE,Charles Leonard Hamblin,none (unique language)
35,1957,FORTRAN I (implementation),John W. Backus at IBM,FORTRAN
36,1957–58,UNICODE,Remington Rand UNIVAC,MATH-MATIC
37,1957,COMIT (concept),Victor Yngve,none (unique language)
38,1958,FORTRAN II,Team led by John W. Backus at IBM,FORTRAN I
39,1958,ALGOL 58 (IAL),ACM/GAMM,"FORTRAN, IT, Sequentielle Formelübersetzung"
40,1958,IPL V,"Allen Newell, Cliff Shaw, Herbert A. Simon",IPL II
41,1959,APT,Douglas T. Ross,NaN
42,1959,FACT,"Fletcher R. Jones, Roy Nutt, Robert L. Patrick",none (unique language)
43,1959,COBOL (concept),The CODASYL Committee,"FLOW-MATIC, COMTRAN, FACT"
44,1959,JOVIAL,Jules Schwartz at SDC,ALGOL 58
45,1959,LISP (implementation),John McCarthy,IPL
46,1959,MAD – Michigan Algorithm Decoder,"Bruce Arden, Bernard Galler, and Robert M. Graham",ALGOL 58
47,1959,TRAC (concept),Calvin Mooers,NaN
48,Year,Name,"Chief developer, company",Predecessor(s)

In [25]:
dfs[7]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1970,Forth (implementation),Charles H. Moore,NaN
1,1970,POP-2,Robin Popplestone,POP-1
2,1970,SAIL,"Dan Swinehart, Bob Sproull",ALGOL 60
3,1970,Pascal,"Niklaus Wirth, Kathleen Jensen","ALGOL 60, ALGOL W"
4,1970,BLISS,"Wulf, Russell, Habermann at Carnegie Mellon Un...",ALGOL
5,1971,KRL,"Daniel G. Bobrow at Xerox PARC, Terry Winograd...","KM, FRL (MIT)"
6,1971,Compiler Description Language (CDL),Cornelis H.A. Koster at University of Nijmegen,NaN
7,1972,Smalltalk-72,"Alan Kay, Adele Goldberg, Dan Ingalls, Xerox PARC",Simula 67
8,1972,PL/M,Gary Kildall at Digital Research,"PL/I, ALGOL, XPL"
9,1972,C,Dennis Ritchie,"B, BCPL, ALGOL 68"
10,1972,INTERCAL,"Don Woods, James M. Lyon",none (unique language)
11,1972,Prolog,Alain Colmerauer,2-level W-Grammar
12,1972,Structured Query language (SQL),IBM,"ALPHA, Quel (Ingres)"
13,1973,COMAL,"Børge Christensen, Benedict Løfstedt","Pascal, BASIC"
14,1973,ML,Robin Milner,NaN
15,1973,LIS,Jean Ichbiah et al. at CII Honeywell Bull,"Pascal, Sue"
16,1973,Speakeasy-3,"Stanley Cohen, Steven Pieper at Argonne Nation...",Speakeasy-2
17,1974,CLU,Barbara Liskov,"ALGOL 60, Lisp, Simula"
18,1974,GRASS,Thomas A. DeFanti,BASIC
19,1974,BASIC FOUR,MAI BASIC Four Inc.,Business BASIC
20,1974,PROSE modeling language,CDC 6600 Cybernet Services,"SLANG, FORTRAN"
21,1975,ABC,Leo Geurts and Lambert Meertens,SETL
22,1975,Irvine Dataflow (concept),"Arvind?, University of California, Irvine",NaN
23,1975,PROSE modeling language Time-Sharing Version,CDC 6400 Cybernet KRONOS Services,"SLANG, FORTRAN"
24,1975,Scheme,"Gerald Jay Sussman, Guy L. Steele Jr.",LISP
25,1975,Altair BASIC,"Bill Gates, Paul Allen",BASIC
26,1975,CS-4,"James S. Miller, Benjamin M. Brosgol et al. at...","ALGOL 68, BLISS, ECL, HAL"
27,1975,Modula,Niklaus Wirth,Pascal
28,1976,Plus,"Allan Ballard, Paul Whaley at the University o...","Pascal, Sue"
29,1976,Smalltalk-76,Xerox PARC,Smalltalk-72
30,1976,Mesa,Xerox PARC,ALGOL
31,1976,Ratfor,Brian Kernighan,"C, FORTRAN"
32,1976,S,John Chambers at Bell Labs,"APL, PPL, Scheme"
33,1976,SAS,SAS Institute,NaN
34,1976,Integer BASIC,Steve Wozniak,BASIC
35,1977,FP,John Backus,none (unique language)
36,1977,Bourne Shell (sh),Stephen R. Bourne,none (unique language)
37,1977,Commodore BASIC,Jack Tramiel,BASIC
38,1977,IDL,David Stern of Research Systems Inc,Fortran
39,1977,Standard MUMPS,NaN,MUMPS
40,1977,Icon (concept),Ralph Griswold,SNOBOL
41,1977,Euclid,"Butler Lampson at Xerox PARC, Ric Holt and Jam...",NaN
42,1977,Applesoft BASIC,Marc McDonald and Ric Weiland,BASIC
43,1978,RAPT,Pat Ambler and Robin Popplestone,APT
44,1978,C shell,Bill Joy,C
45,1978,RPG III,IBM,"FARGO, RPG, RPG II"
46,1978,HAL/S,designed by Intermetrics for NASA,XPL
47,1978,Applesoft II BASIC,Marc McDonald and Ric Weiland,Applesoft BASIC
48,1975,Irvine Dataflow (implementation),"Arvind and Gostelow, University of California,...",NaN
49,1978?,MATLAB,Cleve Moler at the University of New Mexico,Fortran
50,1978?,SMALL,Nevil Brownlee at the University of Auckland,Algol60
51,1978,VisiCalc,"Dan Bricklin, Bob Frankston marketed by VisiCorp",none (unique language)
52,1979,TI BASIC (TI 99/4A),Texas Instruments,BASIC
53,1979,Modula-2,Niklaus Wirth,"Modula, Mesa"
54,1979,REXX,Mike Cowlishaw at IBM,"PL/I, BASIC, EXEC 2"
55,1979,AWK,"Alfred Aho, Peter J. Weinberger, Brian Kernighan","C, SNOBOL"
56,1979,Icon (implementation),Ralph Griswold,SNOBOL
57,1979,Vulcan dBase-II,Wayne Ratliff,none (unique language)
58,Year,Name,"Chief developer, company",Predecessor(s)

In [24]:
dfs[6]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1960,ALGOL 60,NaN,ALGOL 58
1,1960,COBOL 61 (implementation),The CODASYL Committee,"FLOW-MATIC, COMTRAN"
2,1961,COMIT (implementation),Victor Yngve,none (unique language)
3,1961,GPSS,"Geoffrey Gordon, IBM",none (unique language)
4,1962,FORTRAN IV,IBM,FORTRAN II
5,1962,APL (concept),Kenneth E. Iverson,none (unique language)
6,1962,Simula (concept),Ole-Johan Dahl (mostly),ALGOL 60
7,1962,SNOBOL,"Ralph Griswold, et al.","FORTRAN II, COMIT"
8,1963,Combined Programming Language (CPL) (concept),"Barron, Christopher Strachey, et al.",ALGOL 60
9,1963,SNOBOL3,"Griswold, et al.",SNOBOL
10,1963,ALGOL 68 (concept),"Adriaan van Wijngaarden, et al.",ALGOL 60
11,1963,JOSS I,"Cliff Shaw, RAND",ALGOL 58
12,1964,MIMIC,"H. E. Petersen, et al.",MIDAS
13,1964,COWSEL,"Rod Burstall, Robin Popplestone","CPL, LISP"
14,1964,PL/I (concept),IBM,"ALGOL 60, COBOL, FORTRAN"
15,1964,BASIC,"John George Kemeny, Thomas Eugene Kurtz at Dar...","FORTRAN II, JOSS"
16,1964,IBM RPG,IBM,FARGO
17,1964,Mark-IV,Informatics,NaN
18,1964,Speakeasy-2,Stanley Cohen at Argonne National Laboratory,Speakeasy
19,1964,TRAC (implementation),Calvin Mooers,NaN
20,1964,P′′,Corrado Böhm,none (unique language)
21,1964?,IITRAN,NaN,NaN
22,1965,RPG II,IBM,"FARGO, RPG"
23,1965,MAD/I (concept),University of Michigan,"MAD, ALGOL 60, PL/I"
24,1965,TELCOMP,BBN,JOSS
25,1965,Atlas Autocode,"Tony Brooker, Derrick Morris at Manchester Uni...","ALGOL 60, Autocode"
26,1966,JOSS II,"Chuck Baker, RAND",JOSS I
27,1966,ALGOL W,"Niklaus Wirth, C. A. R. Hoare",ALGOL 60
28,1966,FORTRAN 66,John Backus and his team,FORTRAN IV
29,1966,ISWIM (concept),Peter J. Landin,LISP
30,1966,CORAL 66,"I. F. Currie, M. Griffiths",ALGOL 60
31,1966,APL (implementation)[5],Kenneth E. Iverson,none (unique language)
32,1967,BCPL,Martin Richards,CPL
33,1967,MUMPS,Massachusetts General Hospital,"FORTRAN, TELCOMP"
34,1967,Simula 67 (implementation),"Ole-Johan Dahl, Bjørn Myhrhaug, Kristen Nygaar...",ALGOL 60
35,1967,Interlisp,D.G. Bobrow and D.L. Murphy,Lisp
36,1967,EXAPT,"Herwart Opitz, Wilhelm Simon, Günter Spur, and...",APT
37,1967,SNOBOL4,"Ralph Griswold, et al.",SNOBOL3
38,1967,XPL,"William M. McKeeman, et al. at University of C...",PL/I
39,1968,ALGOL 68 (UNESCO/IFIP standard),"Adriaan van Wijngaarden, Barry J. Mailloux, Jo...",ALGOL 60
40,1968,POP-1,"Rod Burstall, Robin Popplestone",COWSEL
41,1968,DIBOL-8,DEC,DIBOL
42,1968,Forth (concept),Moore,NaN
43,1968,Logo,"Wally Feurzeig, Seymour Papert, Cynthia Solomon",LISP
44,1968,MAPPER,Unisys,CRT RPS
45,1968,REFAL (implementation),Valentin Turchin,none (unique language)
46,1968,TTM (implementation),"Steven Caine and E. Kent Gordon, California In...","GAP, GPM"
47,1968,PILOT,"John Amsden Starkweather, University of Califo...",Computest
48,1969,PL/I (implementation),IBM,"ALGOL 60, COBOL, FORTRAN"
49,1969,B,"Ken Thompson, with contributions from Dennis R...",BCPL
50,1969,Polymorphic Programming Language (PPL),Thomas A. Standish at Harvard University,NaN
51,1969,SETL,Jack Schwartz at Courant Institute of Mathemat...,ALGOL 60
52,1969,TUTOR,Paul Tenczar & University of Illinois at Urban...,NaN
53,1969,Edinburgh IMP,Edinburgh University,"ALGOL 60, Autocode, Atlas Autocode"
54,Year,Name,"Chief developer, company",Predecessor(s)

In [23]:
dfs[4]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1804,Jacquard machine,Joseph Marie Jacquard,none (unique language)
1,1879,Begriffsschrift,Gottlob Frege,none (unique language)
2,1943–45,Plankalkül (year of conceptualization),Konrad Zuse,none (unique language)
3,1943–46,ENIAC coding system,"John von Neumann, John Mauchly, J. Presper Eck...",none (unique language)
4,1946,ENIAC Short Code,Richard Clippinger and John von Neumann after ...,none (unique language)
5,1947-52,ARC/Birkbeck Assembler,Kathleen Booth,ENIAC Short Code[1]
6,1948,Plankalkül (year of concept publication),Konrad Zuse,none (unique language)
7,1949,EDSAC Initial Orders,David Wheeler,ENIAC coding system
8,1949,Short Code (originally known as Brief Code),John Mauchly and William F. Schmitt,ENIAC Short Code
9,Year,Name,"Chief developer, company",Predecessor(s)

In [26]:
dfs[8]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1980,Ada 80 (MIL-STD-1815),Jean Ichbiah at CII Honeywell Bull,"ALGOL 68, Green"
1,1980,C with classes,Bjarne Stroustrup[6],"C, Simula 67"
2,1980,Applesoft III,Apple Computer,Applesoft II BASIC
3,1980,Apple III Microsoft BASIC,Microsoft,Microsoft BASIC
4,1980–81,CBASIC,Gordon Eubanks,"BASIC, Compiler Systems, Digital Research"
...,...,...,...,...
63,1989,VisSim,"Peter Darnell, Visual Solutions",NaN
64,1989,LPC,Lars Pensjö,NaN
65,1989,Bash,Brian Fox,"Bourne shell, C shell, KornShell"
66,1989,Magik,"Arthur Chance, of Smallworld Systems Ltd",Smalltalk
67,Year,Name,"Chief developer, company",Predecessor(s)

In [27]:
dfs[9]

,Year,Name,"Chief developer, company",Predecessor(s)
0,1990,Sather,Steve Omohundro,Eiffel
1,1990,AMOS BASIC,François Lionet and Constantin Sotiropoulos,STOS BASIC
2,1990,AMPL,"Robert Fourer, David Gay and Brian Kernighan a...",NaN
3,1990,Object Oberon,"H Mössenböck, J Templ, R Griesemer",Oberon
4,1990,J,"Kenneth E. Iverson, Roger Hui at Iverson Software","APL, FP"
...,...,...,...,...
69,1999,C99,C99 ISO/IEC 9899:1999,C90
70,1999,Gambas,Benoît Minisini,"Visual Basic, Java"
71,1999,Game Maker Language (GML),Mark Overmars,Game Maker
72,1999,Harbour,Antonio Linares,"dBase, Clipper"
73,Year,Name,"Chief developer, company",Predecessor(s)

In [28]:
dfs[10]

,Year,Name,"Chief developer, company",Predecessor(s)
0,2000,Join Java,G Stewart von Itzstein,Java
1,2000,DarkBASIC,The Game Creators,NaN
2,2000,C#,"Anders Hejlsberg, Microsoft (ECMA)","C, C++, Java, Delphi, Modula-2"
3,2001,Joy,Manfred von Thun,"FP, Forth"
4,2001,AspectJ,"Gregor Kiczales, Xerox PARC","Java, Common Lisp"
5,2001,D,"Walter Bright, Digital Mars","C, C++, C#, Java"
6,2001,Processing,Casey Reas and Benjamin Fry,"Java, C, C++[8]"
7,2001,Visual Basic .NET,Microsoft,Visual Basic
8,2001,GDScript (GDS),"Juan Linietsky, Ariel Manzur (OKAM Studio)",Godot
9,2001,Shakespeare Programming Language,"Jon Åslund, Karl Hasselström",NaN
10,2002,Io,Steve Dekorte,"Self, NewtonScript, Lua"
11,2002,Gosu,Guidewire Software,GScript
12,2002,Scratch,"Mitchel Resnick, John Maloney, Natalie Rusk, E...","Logo, Smalltalk, Squeak, E-Toys, HyperCard, Ag..."
13,2003,Nemerle,University of Wrocław,"C#, ML, MetaHaskell"
14,2003,Factor,Slava Pestov,"Joy, Forth, Lisp"
15,2003,Scala,Martin Odersky,"Smalltalk, Java, Haskell, Standard ML, OCaml"
16,2003,C++03,C++ ISO/IEC 14882:2003,"C++, Standard C, C"
17,2003,Squirrel,Alberto Demichelis,Lua
18,2003,Boo,Rodrigo B. de Oliveira,"Python, C#"
19,2004,Subtext,Jonathan Edwards,none (unique language)
20,2004,Alma-0,"Krzysztof Apt, Centrum Wiskunde & Informatica",none (unique language)
21,2004,FreeBASIC,Andre Victor,QBasic
22,2004,Groovy,James Strachan,Java
23,2004,Little b,"Aneil Mallavarapu, Harvard Medical School, Dep...",Lisp
24,2005,Fantom,"Brian Frank, Andy Frank","C#, Scala, Ruby, Erlang"
25,2005,F#,"Don Syme, Microsoft Research","OCaml, C#, Haskell"
26,2005,Haxe,Nicolas Cannasse,"ActionScript, OCaml, Java"
27,2005,Oxygene,RemObjects Software,"Object Pascal, C#"
28,2005,PWCT,Mahmoud Samir Fayed,none (unique language)
29,2005,Seed7,Thomas Mertes,none (unique language)
30,2006,Cobra,Chuck Esterbrook,"Python, C#, Eiffel, Objective-C"
31,2006,Windows PowerShell,Microsoft,"C#, ksh, Perl, CL, DCL, SQL"
32,2006,OptimJ,Ateji,Java
33,2006,Fortress,Guy L. Steele Jr.,"Scala, ML, Haskell"
34,2006,Vala,GNOME,C#
35,2007,Ada 2005,Ada Rapporteur Group,Ada 95
36,2007,Agda,Ulf Norell,"Coq, Epigram, Haskell"
37,2007,QB64,"Galleon, QB64Team",QBasic
38,2007,Clojure,Rich Hickey,"Lisp, ML, Haskell, Erlang"
39,2007,LOLCODE,Adam Lindsay,none (unique language)
40,2007,Oberon-07,Wirth,Oberon
41,2007,Swift (parallel scripting language),"University of Chicago, Argonne National Labora...",NaN
42,2008,Nim,Andreas Rumpf,"Python, Lisp, Object Pascal"
43,2008,Genie,Jamie McCracken,"Python, Boo, D, Object Pascal"
44,2008,Pure,Albert Gräf,Q
45,2009,Chapel,"Brad Chamberlain, Cray Inc.","HPF, ZPL"
46,2009,Go,Google,"C, Oberon, Limbo, Smalltalk"
47,2009,CoffeeScript,Jeremy Ashkenas,"JavaScript, Ruby, Python, Haskell"
48,2009,Idris,Edwin Brady,"Haskell, Agda, Coq"
49,2009,Parasail,"S. Tucker Taft, AdaCore","Modula, Ada, Pascal, ML"
50,2009,Whiley,David J. Pearce,"Java, C, Python"
51,2009,Dafny,K. Rustan M. Leino,"Java, Spec#"
52,Year,Name,"Chief developer, company",Predecessor(s)

In [30]:
dfs[11]

,Year,Name,"Chief developer, company",Predecessor(s)
0,2010,Rust,"Graydon Hoare, Mozilla","Alef, C++, Camlp4, Erlang, Hermes, Limbo, Napi..."
1,2011,C11,C11 ISO/IEC 9899:2011,C99
2,2011,Ceylon,"Gavin King, Red Hat",Java
3,2011,Dart,Google,"Java, JavaScript, CoffeeScript, Go"
4,2011,C++11,C++ ISO/IEC 14882:2011,"C++, Standard C, C"
5,2011,Kotlin,JetBrains,"Java, Scala, Groovy, C#, Gosu"
6,2011,Red,Nenad Rakočević,"Rebol, Scala, Lua"
7,2011,Opa,MLstate,"OCaml, Erlang, JavaScript"
8,2012,Elixir,José Valim,"Erlang, Ruby, Clojure"
9,2012,Elm,Evan Czaplicki,"Haskell, Standard ML, OCaml, F#"
10,2012,TypeScript,"Anders Hejlsberg, Microsoft","JavaScript, CoffeeScript"
11,2012,Julia,"Jeff Bezanson, Stefan Karpinski, Viral Shah, A...","MATLAB, Lisp, C, Fortran, Mathematica[9] (stri..."
12,2012,P,"Vivek Gupta, Ethan Jackson, Shaz Qadeer, Srira...",NaN
13,2012,Ada 2012,ARA and Ada Europe (ISO/IEC 8652:2012),"Ada 2005, ISO/IEC 8652:1995/Amd 1:2007"
14,2013,P4,P4 Language Consortium (P4.org),NaN
15,2013,PureScript,Phil Freeman,Haskell
16,2013,Hopscotch,Hopscotch Technologies,Scratch
17,2013,Cuneiform,Jörgen Brandt,Swift (parallel scripting language)
18,2013,Lean,Microsoft Research,"ML (programming language), Coq, Haskell, Agda ..."
19,2014,Crystal,"Ary Borenszweig, Manas Technology Solutions","Ruby, C, Rust, Go, C#, Python"
20,2014,Hack,Facebook,PHP
21,2014,Swift,Apple Inc.,"Objective-C, Rust, Haskell, Ruby, Python, C#, CLU"
22,2014,C++14,C++ ISO/IEC 14882:2014,"C++, Standard C, C"
23,2014,Solidity,"Gavin Wood, Ethereum","JavaScript, C++, Python"
24,2015,Raku,"Larry Wall, The Rakudo Team","Perl, Haskell, Python, Ruby"
25,2015,Zig,Andrew Kelley,"C, C++, LLVM IR, Go, Rust"
26,2016,Reason,Jordan Walke,"JavaScript, OCaml[11]"
27,2016,Ring,Mahmoud Samir Fayed,"Lua, Python, Ruby, C, C#, BASIC, QML, xBase, S..."
28,2017,C++17,C++ ISO/IEC 14882:2017,"C++, Standard C, C"
29,2017,Ballerina,"WSO2, Open Source[13]","Java, Javascript, Go, Rust, C#"
30,2017,Q#,Microsoft,"C#, F#, Python"
31,2018,C17,ISO/IEC 9899:2018,C11
32,2018,Fortran 2018,ISO/IEC JTC1/SC22/WG5 N2150:2018,Fortran 2008
33,2019,Bosque,"Mark Marron, Microsoft","JavaScript, TypeScript, ML"
34,Year,Name,"Chief developer, company",Predecessor(s)

#### Reading SQL DB

In [31]:
import sqlite3

In [32]:
con = sqlite3.connect("E:\DATA SETS\database.sqlite")
df = pd.read_sql_query('select * from iris', con)
con.close()

In [33]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica